### ISSUE TITLE
ubiconfig can load broken data for certain fields due to implicit YAML types

### ISSUE THREAD

**Issue by rohanpm** [release-engineering/ubi-config#34]
Due to implicit conversion of data from input YAML files, ubi-config can sometimes produce incorrect data.  For example, "stream: 1.10" will end up wrongly being loaded as stream "1.1".

This could potentially lead to quite serious bugs in users of ubi-config.

## Steps to reproduce

Create test.yaml

```
content_sets:
  rpm:
    output: ubi-7-for-atomic-rpms
    input: rhel-atomic-host-rpms
  srpm:
    output: ubi-7-for-atomic-source-rpms
    input: rhel-atomic-host-source-rpms
  debuginfo:
    output: ubi-7-for-atomic-debuginfo-rpms
    input: rhel-atomic-host-debug-rpms

arches:
 - x86_64
packages:
  include:
  - libdnf.*
  exclude: []

modules:
  include:
  - name: ant
    stream: 1.10
    profiles:
    - foobar
```

Run:

```
$ python
Python 2.7.15 (default, Oct 15 2018, 15:26:09) 
[GCC 8.2.1 20180801 (Red Hat 8.2.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ubiconfig
>>> config = ubiconfig.get_loader('.').load('test.yaml')
>>> config.modules.whitelist[0].stream
'1.1'
>>> 
```

## Actual behavior

Output stream is incorrect value "1.1"

## Expected behavior

Output stream is correct value "1.10", identical as in given YAML file

## Additional info

It's possible to disable implicit conversion by passing Loader=BaseLoader to YAML load calls.
